### ISSUE TITLE
Target .NET Core

### ISSUE THREAD

**Issue by corenting** [yageek/lambert-cs#1]
The code in itself can be compiled for .NET Core. Is it possible to build a version for this framework and include it in the Nuget package ?

**Comment by yageek** [comment]
Inside the README you should be able to find the nugget command. 

The package URL is the following: https://www.nuget.org/packages/LambertCS/

I'm not a regular user of .NET. If you miss any information, let me know and I will try to help.

**Comment by corenting** [comment]
Il y a eu un malentendu, je vais donc expliquer en français.
Le problème ne vient pas de la commande Nuget, mais du fait que dans le csproj le framework ciblé est ```<TargetFrameworkVersion>v4.5</TargetFrameworkVersion>``` . La librairie n'incluant pas du code spécifique à ce framework, il faudrait plus cibler ```netstandard1.0``` ( cf https://docs.microsoft.com/en-us/nuget/schema/target-frameworks ) pour être compatible avec les différentes plateformes .NET existantes (.NET Core, Xamarin...)

**Comment by yageek** [comment]
As I am not really used to Microsoft development, could you provide me some feedback after I have created a PR ? Should I redeploy a new version or can I update the previous one ?

**EDIT**: The #2 PR is opened. Is there something else to do ?

**Comment by corenting** [comment]
I dont' really know about deployement / Nuget packaging sorry, but the change looks OK to me

**Comment by yageek** [comment]
Closes #2
